#!/bin/bash -xev 

#########################################################################################################
#
# Name nagios.sh
#
# Script to auto install the nagios service, confuration of users must be done manually @ this time
# Author: Mark B.
# December 3 2016
#########################################################################################################


echo "Updating the System now"
sudo yum update -y

echo "Step 1: Install Required Dependencies"


echo “Installing Dependencies”

yum install -y httpd php zip unzip gcc glibc glibc-common gd gd-devel make net-snmp

wait

echo "Step 2: Create Nagios User and Group"

useradd nagios

groupadd nagcmd

usermod -G nagcmd nagios

usermod -G nagcmd apache

echo "Step 3: Download Nagios Core 4.2.0 and Nagios Plugin 2.1.2"

mkdir /root/nagios

wait

cd /root/nagios

echo “Installing wget”

yum -y install wget

wait

wget http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.0.tar.gz

wait

wget https://www.nagios-plugins.org/download/nagios-plugins-2.1.2.tar.gz

echo "Step 4: Extract Nagios Core and its Plugins"

tar -xvf nagios-4.2.0.tar.gz
wait
tar -xvf nagios-plugins-2.1.2.tar.gz
wait

cd nagios-4.2.0

./configure --with-command-group=nagcmd

wait

make all

make install

make install-init

make install-commandmode

make install-config

echo "********************************Step 5: Customizing Nagios Configuration*********************************"

echo "I will have to do this manually, the admin email address needs to be placed in"

echo "Step 6: Install and Configure Web Interface for Nagios"

# Setup password and account at the end

make install-webconf

systemctl restart httpd

echo "Step 7: Compile and Install Nagios Plugin"

cd /root/nagios

cd nagios-plugins-2.1.2/
wait

./configure --with-nagios-user=nagios --with-nagios-group=nagios
wait

make

make install

wait

systemctl enable nagios
wait
systemctl start nagios
wait

#htpasswd -s -c /usr/local/nagios/etc/htpasswd.users nagiosadmin
